
-- Supabase SQL schema for the Control Systems Virtual Laboratory
create table if not exists public.lab_submissions (
    id bigint generated by default as identity primary key,
    submitted_at timestamptz not null default now(),
    student_name text not null,
    roll_no text not null,
    experiment text not null,
    equation text,
    coefficients text,
    k double precision,
    system_order integer,
    status text,
    routh_sign_changes integer,
    poles text,
    prediction text,
    boundary text,
    observations text,
    explanation text,
    reflection text
);

alter table public.lab_submissions enable row level security;

-- The app uses the Supabase REST API with the configured API key.
-- For a classroom MVP, allow inserts/selects through the API role used by the app.
-- If you expose the anon key publicly, use a stronger authentication/RLS policy
-- before production institutional deployment.

create policy "allow lab insert"
on public.lab_submissions
for insert
to anon, authenticated
with check (true);

create policy "allow lab select"
on public.lab_submissions
for select
to anon, authenticated
using (true);
